import { Routes } from '@angular/router';
import { AlertsComponent } from 'app/admin/alerts/alerts/alerts.component';
import { AdoptionsComponent } from 'app/admin/adoptions/adoptions/adoptions.component';
import { AppointmentsComponent } from 'app/admin/appointments/appointments/appointments.component';
import { ArticlesComponent } from 'app/admin/articles/articles/articles.component';
import { ArticleEditorComponent } from 'app/admin/articles/article-editor/article-editor.component';
import { GeneralConsultationsComponent } from 'app/admin/generalConsultations/general-consultations/general-consultations.component';
import { PrivateConsultationsComponent } from 'app/admin/privateConsultations/private-consultations/private-consultations.component';
import { PetsComponent } from 'app/admin/pets/pets/pets.component';
import { ProfileComponent } from 'app/admin/profile/profile/profile.component';
import { GeneralConsultationEditorComponent } from 'app/admin/generalConsultations/general-consultation-editor/general-consultation-editor.component';
import { AlertEditorComponent } from 'app/admin/alerts/alert-editor/alert-editor.component';
import { PetEditorComponent } from 'app/admin/pets/pet-editor/pet-editor.component';
import { ConfigFormComponent } from 'app/admin/adoptions/config-form/config-form.component';

export const AdminLayoutRoutes: Routes = [
    { path: '',      component: ProfileComponent },
    { path: 'perfil',      component: ProfileComponent },
    { path: 'alertas',      component: AlertsComponent },
    { path: 'edicion-alerta',      component: AlertEditorComponent },
    { path: 'edicion-alerta/:id',      component: AlertEditorComponent },
    { path: 'adopciones',      component: AdoptionsComponent },
    { path: 'configuracion-formulario',      component: ConfigFormComponent },
    { path: 'citas',      component: AppointmentsComponent },
    { path: 'articulos',      component: ArticlesComponent },
    { path: 'edicion-articulo',      component: ArticleEditorComponent },
    { path: 'edicion-articulo/:id',      component: ArticleEditorComponent },
    { path: 'consultas-generales',      component: GeneralConsultationsComponent },
    { path: 'edicion-consulta-general',      component: GeneralConsultationEditorComponent },
    { path: 'edicion-consulta-general/:id',      component: GeneralConsultationEditorComponent },
    { path: 'consultas-privadas',      component: PrivateConsultationsComponent },
    { path: 'mascotas',      component: PetsComponent },
    { path: 'edicion-mascota',      component: PetEditorComponent },
    { path: 'edicion-mascota/:id',      component: PetEditorComponent }
];
